import torch
import torch.nn as nn
import torch.nn.functional as F

from typeguard import typechecked
from torchtyping import TensorType, patch_typeguard
from typing import Tuple

from .decoder import Decoder
from .encoder import Encoder

patch_typeguard()

class VAE(nn.Module):
    def __init__(self, input_dim: int, latent_dim: int, hidden_dim: int=100):
        """Initialize the VAE model.
        
        Args:
            obs_dim (int): Dimension of the observed data x, int
            latent_dim (int): Dimension of the latent variable z, int
            hidden_dim (int): Hidden dimension of the encoder/decoder networks, int
        """
        super().__init__()
        self.latent_dim = latent_dim
        self.encoder = Encoder(input_dim, latent_dim, hidden_dim=hidden_dim)
        self.decoder = Decoder(input_dim, latent_dim, hidden_dim=hidden_dim)
    
    @typechecked
    def sample_with_reparametrization(self, mu: TensorType['batch_size', 'latent_dim'], 
                                      logsigma: TensorType['batch_size', 'latent_dim']) -> TensorType['batch_size', 'latent_dim']:
        """Draw sample from q(z) with reparametrization.
        
        We draw a single sample z_i for each data point x_i.
        
        Args:
            mu: Means of q(z) for the batch, shape [batch_size, latent_dim]
            logsigma: Log-sigmas of q(z) for the batch, shape [batch_size, latent_dim]
        
        Returns:
            z: Latent variables samples from q(z), shape [batch_size, latent_dim]
        """
        ##########################################################
        # YOUR CODE HERE        
        latent_dim = self.latent_dim

        eps = torch.normal(0, 1, (mu.shape[0], latent_dim))
        z = mu + torch.exp(logsigma) * eps

        return z
        ##########################################################
    
    @typechecked
    def kl_divergence(self, mu: TensorType['batch_size', 'latent_dim'], logsigma: TensorType['batch_size', 'latent_dim']) -> TensorType['batch_size']:
        """Compute KL divergence KL(q_i(z)||p(z)) for each q_i in the batch.
        
        Args:
            mu: Means of the q_i distributions, shape [batch_size, latent_dim]
            logsigma: Logarithm of standard deviations of the q_i distributions,
                      shape [batch_size, latent_dim]
        
        Returns:
            kl: KL divergence for each of the q_i distributions, shape [batch_size]
        """
        ##########################################################
        # YOUR CODE HERE
        latent_dim = self.latent_dim

        kl = 0.5 * torch.sum(torch.exp(2 * logsigma) + mu ** 2 - 1 - 2 * logsigma, dim = 1)

        return kl
        ##########################################################
    
    @typechecked
    def elbo(self, x: TensorType['batch_size', 'input_dim']) -> TensorType['batch_size']:
        """Estimate the ELBO for the mini-batch of data.
        
        Args:
            x: Mini-batch of the observations, shape [batch_size, input_dim]
        
        Returns:
            elbo_mc: MC estimate of ELBO for each sample in the mini-batch, shape [batch_size]
        """
        ##########################################################
        # YOUR CODE HERE

        latent_dim = self.latent_dim
        mini_batch_size = x.shape[1]

        mu, logsigma = self.encoder(x)
        z = self.sample_with_reparametrization(mu, logsigma)
        theta = self.decoder(z)

        kl = self.kl_divergence(mu, logsigma)
        log_likelihood = torch.sum(x * torch.log(theta) + (1 - x) * torch.log(1 - theta), dim = 1)
        l = log_likelihood - kl

        return l
        ##########################################################
        
    @typechecked
    def sample(self, num_samples: int, device: str='cpu') -> Tuple[
        TensorType['num_samples', 'latent_dim'],
        TensorType['num_samples', 'input_dim'],
        TensorType['num_samples', 'input_dim']]:
        """Generate new samples from the model.
        
        Args:
            num_samples: Number of samples to generate.
        
        Returns:
            z: Sampled latent codes, shape [num_samples, latent_dim]
            theta: Parameters of the output distribution, shape [num_samples, input_dim]
            x: Corresponding samples generated by the model, shape [num_samples, input_dim]
        """
        ##########################################################
        # YOUR CODE HERE

        latent_dim = self.latent_dim

        zz = torch.normal(0, 1, (num_samples, latent_dim))
        theta = self.decoder(zz)
        x = torch.bernoulli(theta)

        return zz, theta, x
        ##########################################################